<?php
/**
 * Plugin Name:       Responsive Navigation
 * Description:       A responsive core Navigation block
 * Requires at least: 5.8
 * Requires PHP:      7.0
 * Version:           0.1.0
 * Author:            Dave Smith
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       responsive-nav-block
 *
 * @package getdave
 */





// Init. Register scripts and styles.
function sidebar_plugin_register()
{
    // Deps generated by @wordpress/scripts.
    $manifest = include 'build/index.asset.php';

    wp_register_script(
        'getdave-responsive-nav-block-js',
        plugins_url('build/index.js', __FILE__),
        $manifest['dependencies'],
        $manifest['version'],
    );

    wp_register_style(
        'getdave-responsive-nav-block-css',
        plugins_url('build/style-index.css', __FILE__)
    );

    wp_enqueue_block_style(
        'core/navigation',
        array(
        'handle' => 'getdave-responsive-nav-block-css',
        )
    );
}
add_action('init', 'sidebar_plugin_register');


function getdave_responsive_nav_block_block_data( $parsed_block )
{
    if ('core/navigation' === $parsed_block['blockName'] ) {

        $class_names = array_filter(
            array(
            'hide-on-desktop' => isset($parsed_block['attrs']['hideOnDesktop']),
            'hide-on-tablet'  => isset($parsed_block['attrs']['hideOnTablet']),
            'hide-on-mobile'  => isset($parsed_block['attrs']['hideOnMobile']),
            ),
        );

        $class_names = implode(' ', array_keys($class_names));

        if (empty($parsed_block['attrs']['className']) ) {
            $parsed_block['attrs']['className'] = $class_names;
        } else {
            $parsed_block['attrs']['className'] = $parsed_block['attrs']['className'] . ' ' . $class_names;
        }
    }

    return $parsed_block;
}

add_filter('render_block_data', 'getdave_responsive_nav_block_block_data');
